
export enum MessageRole {
  USER = 'user',
  MODEL = 'model',
}

export interface Citation {
  index: number;
  text: string;
}

export interface Message {
  role: MessageRole;
  text: string;
  documentId?: string;
  documentTitle?: string;
  summary?: string; // Add summary for the new document card
  timestamp?: string;
  citations?: Citation[];
}

export interface UploadedFile {
    name: string;
    type: string;
    base64Data: string;
}

export interface GeneratedDocument {
    id: string;
    title: string;
    content: string; // Raw text content streamed from AI or written by user
    generatedHtml: string; // The visualized HTML generated by a canvas tool
    createdAt: string;
}

export enum CanvasTool {
  INFOGRAPHIC = 'Đồ họa thông tin',
  QUIZ = 'Bài kiểm tra',
  FLASHCARDS = 'Thẻ ghi nhớ',
  MIND_MAP = 'Bản đồ tư duy',
}

// New enum for the tools menu in ChatInput
export enum Tool {
    CANVAS = 'Canvas',
    DEEP_RESEARCH = 'Deep Research',
    VIDEO = 'Tạo video bằng Veo',
    IMAGEN = 'Tạo hình ảnh bằng Imagen',
    GUIDED_LEARNING = 'Học có hướng dẫn',
}